# These are supported funding model platforms

github: ['sophiashirashaki', 'kennedy-ex', 'riz-ex', 'aryazakaria01', 'FeriEXP']
community_bridge: kennedy-project
custom: ['https://t.me/projectsupdates', 'https://t.me/AkoUpdate']
